server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
spring:
  aop:
    auto: true
  mail:
    host: 220.181.12.11   #linux有时候不能有效的进行域名解析，所以我们直接用smtp.163.com来ping一下获取真实的ip地址
    username: XXXXXX  #填写你的邮箱地址(发送人)
    password: XXXXXX  #你的邮箱密码
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          port: 465  #使用465端口 因为在服务器上25端口不能用
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          starttls:
            enable: true
            required: true
    port: 465
